trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'  
    jdkSource: 'PreInstalled'

- script: java -version
  displayName: 'Check Java Version'

- script: |
    javac HelloDevOps.java  
    java HelloDevOps        
  displayName: 'Build and Run Java Program'
