trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'  
    jdkArchitecture: 'x64'

- script: |
    javac HelloDevOps.java  
    java HelloDevOps        
  displayName: 'Build and Run Java Program'