trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
    jdkSource: 'PreInstalled'

- script: |
    javac HelloDevOps.java  
    java HelloDevOps        
  displayName: 'Build and Run Java Program'